language: python

python:
  - "3.2"
  - "3.3"
  - "3.4"

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - sudo apt-get -y update
  - sudo apt-get -y install python3-pyside

# command to run tests
script:
  - python qtodotxt/test/run-tests.py
