language: python
python:
  - "3.4"
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
# command to install dependencies
install: "pip install PySide"
# command to run tests
script:
  - python qtodotxt/test/run-tests.py