language: python

python:
  - "3.2"
  - "3.3"
  - "3.4"

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - sudo apt-get update
  - sudo apt-get -y install python3-pyside
  - export PYTHONPATH="$PYTHONPATH:/usr/lib/python3/dist-packages"
  - pip install flake8

# command to run tests
script:
  - echo $PYTHONPATH
  - ls /usr/lib/python3/dist-packages/PySide
  - python -c "import sys; print('/usr/lib/python3/dist-packages' in sys.path)"
  - python -c "import PySide; print(PySide.__version__)"
  - flake8 qtodotxt && qtodotxt/test/run-tests.py
